import fs from 'fs';
import { blur3, frameCandidates, teePresence, solvePath, smoothTrack } from '../docs/core.js';
const id = process.argv[2]; const dir='/home/claude/fgtest/';
const m = JSON.parse(fs.readFileSync(dir+id+'.json')); const fr=fs.readFileSync(dir+id+'.frames');
const {AW,AH,n,pts,W0}=m; const sc=AW/W0; const first=pts[0], last=pts[pts.length-1];
const tapF=Math.max(0,first[0]-8); const S={f:tapF,x:first[1]*sc,y:first[2]*sc}, E={f:last[0],x:last[1]*sc,y:last[2]*sc};
const G={}; const get=(f)=>G[f]??(G[f]=blur3(fr.subarray(f*AW*AH,(f+1)*AW*AH),AW,AH));
const cands={}; for(let f=S.f+1;f<E.f;f++) cands[f]=frameCandidates(get(f-2),get(f),get(f+2),AW,AH);
const cr=fs.readFileSync(dir+id+'.crops'); const C=m.C; const crops=[]; for(let i=0;i<n;i++) crops.push(cr.subarray(i*C*C,(i+1)*C*C));
const absent=teePresence(crops,C,C,tapF,E.f); console.log('absent',Array.from(absent.slice(tapF,tapF+20)).map(v=>v.toFixed(1)).join(' '));
const path=solvePath(cands,{x:S.x,y:S.y,f0:tapF,absent},E,{},{fps:50,H:AH,...JSON.parse(process.env.OPTS||'{}')});
const v={}; for(const [f,x,y] of pts) v[f]=[x*sc,y*sc];
console.log(path.map(p=>`${p.f}:${p.x.toFixed(0)},${p.y.toFixed(0)}${v[p.f]?'('+v[p.f][0].toFixed(0)+','+v[p.f][1].toFixed(0)+')':''}`).join(' '));
const sm=smoothTrack(path); console.log(sm.filter((p,i)=>i%5==0).map(p=>`${p.f}:${p.x.toFixed(0)},${p.y.toFixed(0)}`).join(' '));
